// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_DEVICECTRL_H
#define UI_DEVICECTRL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DeviceCtrl
extern void ui_DeviceCtrl_screen_init(void);
extern void ui_DeviceCtrl_screen_destroy(void);
extern lv_obj_t * ui_DeviceCtrl;
extern void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern void ui_event_Switch2(lv_event_t * e);
extern lv_obj_t * ui_Switch2;
extern void ui_event_Switch3(lv_event_t * e);
extern lv_obj_t * ui_Switch3;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
