// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"
#include "led_handler.h"
#include "nsh_terminal.h"
#include "buzzer.h"

lv_obj_t * ui_DeviceCtrl = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_Switch2 = NULL;
lv_obj_t * ui_Switch3 = NULL;
lv_obj_t * ui_Button1 = NULL;
static lv_timer_t * ui_DeviceCtrl_sync_timer = NULL;

// event funtions
void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Led1Change(e);
    }
}

void ui_event_Switch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Led2Change(e);
    }
}

void ui_event_Switch3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Led3Change(e);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_HomeScreen_screen_init);
    }
}

// build funtions

static void piano_press_cb(lv_event_t *e)
{
    note_name_t note = (note_name_t)(uintptr_t)lv_event_get_user_data(e);
    buzzer_on(note);
}

static void piano_release_cb(lv_event_t *e)
{
    note_name_t note = (note_name_t)(uintptr_t)lv_event_get_user_data(e);
    buzzer_off(note);
}

static void ui_DeviceCtrl_sync_cb(lv_timer_t * t)
{
    led_sync_all();
}

void ui_DeviceCtrl_screen_init(void)
{
    ui_DeviceCtrl = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_DeviceCtrl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch1 = lv_switch_create(ui_DeviceCtrl);
    lv_obj_set_width(ui_Switch1, 70);
    lv_obj_set_height(ui_Switch1, 35);
    lv_obj_set_x(ui_Switch1, -234);
    lv_obj_set_y(ui_Switch1, -164);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);

    ui_Switch2 = lv_switch_create(ui_DeviceCtrl);
    lv_obj_set_width(ui_Switch2, 70);
    lv_obj_set_height(ui_Switch2, 35);
    lv_obj_set_x(ui_Switch2, -234);
    lv_obj_set_y(ui_Switch2, -94);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);

    ui_Switch3 = lv_switch_create(ui_DeviceCtrl);
    lv_obj_set_width(ui_Switch3, 70);
    lv_obj_set_height(ui_Switch3, 35);
    lv_obj_set_x(ui_Switch3, -232);
    lv_obj_set_y(ui_Switch3, -24);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_CENTER);

    // Home button
    ui_Button1 = lv_button_create(ui_DeviceCtrl);
    lv_obj_set_width(ui_Button1, 90);
    lv_obj_set_height(ui_Button1, 40);
    lv_obj_align(ui_Button1, LV_ALIGN_TOP_LEFT, 10, 10);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x3AACB7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Button1, 8, LV_PART_MAIN);
    lv_obj_t * label = lv_label_create(ui_Button1);
    lv_label_set_text(label, "Home");
    lv_obj_center(label);

    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch2, ui_event_Switch2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch3, ui_event_Switch3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

    led_state_init();
    led_sync_all();

    ui_DeviceCtrl_sync_timer = lv_timer_create(ui_DeviceCtrl_sync_cb, 500, NULL);

    /* Piano keys */
    buzzer_init();

    static const char *note_names[] = {"Do", "Re", "Mi", "Fa", "Sol", "La", "Ti"};
    const int key_w = 60;
    const int key_h = 100;
    const int gap  = 8;

    for (int i = 0; i < 7; i++)
    {
        lv_obj_t *key = lv_button_create(ui_DeviceCtrl);
        lv_obj_set_size(key, key_w, key_h);
        lv_obj_align(key, LV_ALIGN_BOTTOM_LEFT, 8 + i * (key_w + gap), -10);
        lv_obj_set_style_radius(key, 4, LV_PART_MAIN);
        lv_obj_set_style_bg_color(key, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
        lv_obj_set_style_border_width(key, 1, LV_PART_MAIN);
        lv_obj_set_style_border_color(key, lv_color_hex(0x333333), LV_PART_MAIN);

        lv_obj_t *lbl = lv_label_create(key);
        lv_label_set_text(lbl, note_names[i]);
        lv_obj_center(lbl);

        lv_obj_add_event_cb(key, piano_press_cb, LV_EVENT_PRESSED, (void *)(uintptr_t)i);
        lv_obj_add_event_cb(key, piano_release_cb, LV_EVENT_RELEASED, (void *)(uintptr_t)i);
    }

    nsh_terminal_toggle_btn_create(ui_DeviceCtrl);
}

void ui_DeviceCtrl_screen_destroy(void)
{
    if (ui_DeviceCtrl_sync_timer)
    {
        lv_timer_del(ui_DeviceCtrl_sync_timer);
        ui_DeviceCtrl_sync_timer = NULL;
    }

    if(ui_DeviceCtrl) lv_obj_del(ui_DeviceCtrl);

    buzzer_deinit();

    // NULL screen variables
    ui_DeviceCtrl = NULL;
    ui_Switch1 = NULL;
    ui_Switch2 = NULL;
    ui_Switch3 = NULL;
    ui_Button1 = NULL;
}
