// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_FILEEDIT_H
#define UI_FILEEDIT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_FileEdit
extern void ui_FileEdit_screen_init(void);
extern void ui_FileEdit_screen_destroy(void);
extern lv_obj_t * ui_FileEdit;
extern void ui_event_TextArea3(lv_event_t * e);
extern lv_obj_t * ui_TextArea3;
extern lv_obj_t * ui_Keyboard2;
extern void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label2;
extern void ui_event_ButtonHome3(lv_event_t * e);
extern lv_obj_t * ui_ButtonHome3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

