// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"
#include "nsh_terminal.h"

lv_obj_t * ui_HomeScreen = NULL;
lv_obj_t * ui_ButtonTheme = NULL;
lv_obj_t * ui_btnToScreen1 = NULL;
lv_obj_t * ui_btnToScreen2 = NULL;
lv_obj_t * ui_btnToScreen3 = NULL;

lv_obj_t * ui_btnToScreen4 = NULL;
lv_obj_t * ui_btnToScreen5 = NULL;
lv_obj_t * ui_btnToInformation = NULL;
lv_obj_t * ui_btnExitApp = NULL;

static bool ui_theme_dark = false;
static lv_obj_t * ui_title_label = NULL;

void ui_event_ButtonTheme(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        lv_color_t bg;

        ui_theme_dark = !ui_theme_dark;
        if (ui_theme_dark) {
            bg = lv_color_hex(0x282828);
            lv_obj_set_style_text_color(ui_ButtonTheme, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
            lv_obj_set_style_text_color(ui_title_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
        } else {
            bg = lv_color_hex(0xFFFFFF);
            lv_obj_set_style_text_color(ui_ButtonTheme, lv_color_hex(0x000000), LV_PART_MAIN);
            lv_obj_set_style_text_color(ui_title_label, lv_color_hex(0x000000), LV_PART_MAIN);
        }

        lv_obj_set_style_bg_color(ui_HomeScreen, bg, LV_PART_MAIN);
        lv_obj_set_style_bg_color(ui_DeviceCtrl, bg, LV_PART_MAIN);
        lv_obj_set_style_bg_color(ui_ModbusSlave, bg, LV_PART_MAIN);
        lv_obj_set_style_bg_color(ui_FileEdit, bg, LV_PART_MAIN);
        lv_obj_set_style_bg_color(ui_FileExplorer, bg, LV_PART_MAIN);
        lv_obj_set_style_bg_color(ui_MusicPlayer, bg, LV_PART_MAIN);
        lv_obj_set_style_bg_color(ui_Information, bg, LV_PART_MAIN);
        if (ui_theme_dark) {
            lv_obj_set_style_text_color(ui_labelVersion, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
            lv_obj_set_style_text_color(ui_labelUptime, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
            lv_obj_set_style_text_color(ui_labelUptimePrefix, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
        } else {
            lv_obj_set_style_text_color(ui_labelVersion, lv_color_hex(0x000000), LV_PART_MAIN);
            lv_obj_set_style_text_color(ui_labelUptime, lv_color_hex(0x000000), LV_PART_MAIN);
            lv_obj_set_style_text_color(ui_labelUptimePrefix, lv_color_hex(0x000000), LV_PART_MAIN);
        }
    }
}

void ui_event_btnToInformation(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Information, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Information_screen_init);
    }
}

void ui_event_btnToScreen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DeviceCtrl, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_DeviceCtrl_screen_init);
    }
}

void ui_event_btnToScreen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ModbusSlave, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ModbusSlave_screen_init);
    }
}

void ui_event_btnToScreen3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_FileEdit, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_FileEdit_screen_init);
    }
}

void ui_event_btnToScreen4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_FileExplorer, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_FileExplorer_screen_init);
    }
}

void ui_event_btnToScreen5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MusicPlayer, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_MusicPlayer_screen_init);
    }
}

// build functions

static void add_label_to_btn(lv_obj_t * btn, const char * text)
{
    lv_obj_t * label = lv_label_create(btn);
    lv_label_set_text(label, text);
    lv_obj_center(label);
}

void ui_HomeScreen_screen_init(void)
{
    ui_HomeScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_HomeScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN);

    // Title
    ui_title_label = lv_label_create(ui_HomeScreen);
    lv_label_set_text(ui_title_label, "Main Menu");
    lv_obj_set_style_text_font(ui_title_label, &lv_font_montserrat_14, LV_PART_MAIN);
    lv_obj_set_style_text_color(ui_title_label, lv_color_hex(0x000000), LV_PART_MAIN);
    lv_obj_align(ui_title_label, LV_ALIGN_TOP_MID, 0, 30);

    // Theme toggle button
    ui_ButtonTheme = lv_button_create(ui_HomeScreen);
    lv_obj_set_width(ui_ButtonTheme, 130);
    lv_obj_set_height(ui_ButtonTheme, 40);
    lv_obj_align(ui_ButtonTheme, LV_ALIGN_TOP_LEFT, 10, 10);
    lv_obj_set_style_bg_color(ui_ButtonTheme, lv_color_hex(0x3AACB7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonTheme, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ButtonTheme, lv_color_hex(0x000000), LV_PART_MAIN);
    lv_obj_set_style_radius(ui_ButtonTheme, 8, LV_PART_MAIN);
    add_label_to_btn(ui_ButtonTheme, "Switch Theme");

    // Navigation buttons
    ui_btnToScreen1 = lv_button_create(ui_HomeScreen);
    lv_obj_set_width(ui_btnToScreen1, 160);
    lv_obj_set_height(ui_btnToScreen1, 60);
    lv_obj_align(ui_btnToScreen1, LV_ALIGN_CENTER, 0, -100);
    lv_obj_set_style_bg_color(ui_btnToScreen1, lv_color_hex(0x3AACB7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnToScreen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_btnToScreen1, 10, LV_PART_MAIN);
    add_label_to_btn(ui_btnToScreen1, "Device Ctrl");

    ui_btnToScreen2 = lv_button_create(ui_HomeScreen);
    lv_obj_set_width(ui_btnToScreen2, 160);
    lv_obj_set_height(ui_btnToScreen2, 60);
    lv_obj_align(ui_btnToScreen2, LV_ALIGN_CENTER, 0, -50);
    lv_obj_set_style_bg_color(ui_btnToScreen2, lv_color_hex(0x3AACB7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnToScreen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_btnToScreen2, 10, LV_PART_MAIN);
    add_label_to_btn(ui_btnToScreen2, "Modbus Slave");

    ui_btnToScreen3 = lv_button_create(ui_HomeScreen);
    lv_obj_set_width(ui_btnToScreen3, 160);
    lv_obj_set_height(ui_btnToScreen3, 60);
    lv_obj_align(ui_btnToScreen3, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_style_bg_color(ui_btnToScreen3, lv_color_hex(0x3AACB7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnToScreen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_btnToScreen3, 10, LV_PART_MAIN);
    add_label_to_btn(ui_btnToScreen3, "File Edit");

    // File Browser button
    ui_btnToScreen4 = lv_button_create(ui_HomeScreen);
    lv_obj_set_width(ui_btnToScreen4, 160);
    lv_obj_set_height(ui_btnToScreen4, 60);
    lv_obj_align(ui_btnToScreen4, LV_ALIGN_CENTER, 0, 50);
    lv_obj_set_style_bg_color(ui_btnToScreen4, lv_color_hex(0x3AACB7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnToScreen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_btnToScreen4, 10, LV_PART_MAIN);
    add_label_to_btn(ui_btnToScreen4, "File Browser");

    // Music Player button
    ui_btnToScreen5 = lv_button_create(ui_HomeScreen);
    lv_obj_set_width(ui_btnToScreen5, 160);
    lv_obj_set_height(ui_btnToScreen5, 60);
    lv_obj_align(ui_btnToScreen5, LV_ALIGN_CENTER, 0, 100);
    lv_obj_set_style_bg_color(ui_btnToScreen5, lv_color_hex(0x3AACB7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnToScreen5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_btnToScreen5, 10, LV_PART_MAIN);
    add_label_to_btn(ui_btnToScreen5, "Music Player");

    // Information button at bottom
    ui_btnToInformation = lv_button_create(ui_HomeScreen);
    lv_obj_set_width(ui_btnToInformation, 160);
    lv_obj_set_height(ui_btnToInformation, 50);
    lv_obj_align(ui_btnToInformation, LV_ALIGN_BOTTOM_MID, 0, -10);
    lv_obj_set_style_bg_color(ui_btnToInformation, lv_color_hex(0x3AACB7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnToInformation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_btnToInformation, 10, LV_PART_MAIN);
    add_label_to_btn(ui_btnToInformation, "Information");

    // Register events
    lv_obj_add_event_cb(ui_ButtonTheme, ui_event_ButtonTheme, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnToScreen1, ui_event_btnToScreen1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnToScreen2, ui_event_btnToScreen2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnToScreen3, ui_event_btnToScreen3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnToScreen4, ui_event_btnToScreen4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnToScreen5, ui_event_btnToScreen5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnToInformation, ui_event_btnToInformation, LV_EVENT_ALL, NULL);
    nsh_terminal_toggle_btn_create(ui_HomeScreen);
}

void ui_HomeScreen_screen_destroy(void)
{
    if (ui_HomeScreen) lv_obj_del(ui_HomeScreen);

    ui_HomeScreen = NULL;
    ui_ButtonTheme = NULL;
    ui_btnToScreen1 = NULL;
    ui_btnToScreen2 = NULL;
    ui_btnToScreen3 = NULL;
    ui_btnToScreen4 = NULL;
    ui_btnToScreen5 = NULL;
    ui_btnToInformation = NULL;
}
