// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_HOMESCREEN_H
#define UI_HOMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HomeScreen
extern void ui_HomeScreen_screen_init(void);
extern void ui_HomeScreen_screen_destroy(void);
extern lv_obj_t * ui_HomeScreen;
extern void ui_event_ButtonTheme(lv_event_t * e);
extern lv_obj_t * ui_ButtonTheme;
extern void ui_event_btnToScreen1(lv_event_t * e);
extern lv_obj_t * ui_btnToScreen1;
extern void ui_event_btnToScreen2(lv_event_t * e);
extern lv_obj_t * ui_btnToScreen2;
extern void ui_event_btnToScreen3(lv_event_t * e);
extern lv_obj_t * ui_btnToScreen3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
