// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_LEDCTRLTEST_H
#define UI_LEDCTRLTEST_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_LedCtrlTest
extern void ui_LedCtrlTest_screen_init(void);
extern void ui_LedCtrlTest_screen_destroy(void);
extern void ui_LedCtrlTest_screen_relocalize(void);
extern lv_obj_t * ui_LedCtrlTest;
extern void ui_event_Bar1(lv_event_t * e);
extern lv_obj_t * ui_Bar1;
extern void ui_event_Led1Switch(lv_event_t * e);
extern lv_obj_t * ui_Led1Switch;
extern void ui_event_Led2Switch(lv_event_t * e);
extern lv_obj_t * ui_Led2Switch;
extern void ui_event_Led3Switch(lv_event_t * e);
extern lv_obj_t * ui_Led3Switch;
extern void ui_event_GotoModbusTest(lv_event_t * e);
extern lv_obj_t * ui_GotoModbusTest;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

