// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_LedCtrlTest = NULL;
lv_obj_t * ui_Bar1 = NULL;
lv_obj_t * ui_Led1Switch = NULL;
lv_obj_t * ui_Led2Switch = NULL;
lv_obj_t * ui_Led3Switch = NULL;
lv_obj_t * ui_GotoModbusTest = NULL;
lv_obj_t * ui_Label4 = NULL;
// event funtions
void ui_event_Bar1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Bar1ValueChangeEvent(e);
    }
    if(event_code == LV_EVENT_PRESSED) {
        Bar1ValuePressedEvent(e);
    }
}

void ui_event_Led1Switch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Led1ClickedEvent(e);
    }
}

void ui_event_Led2Switch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Led2ClickedEvent(e);
    }
}

void ui_event_Led3Switch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Led3ClickedEvent(e);
    }
}

void ui_event_GotoModbusTest(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ModebusTest, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ModebusTest_screen_init);
    }
}

// build funtions

void ui_LedCtrlTest_screen_init(void)
{
    ui_LedCtrlTest = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_LedCtrlTest, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Bar1 = lv_bar_create(ui_LedCtrlTest);
    lv_bar_set_value(ui_Bar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 150);
    lv_obj_set_height(ui_Bar1, 14);
    lv_obj_set_x(ui_Bar1, -285);
    lv_obj_set_y(ui_Bar1, 4);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar1,
                                                                                           lv_obj_get_style_pad_right(ui_Bar1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Led1Switch = lv_switch_create(ui_LedCtrlTest);
    lv_obj_set_width(ui_Led1Switch, 50);
    lv_obj_set_height(ui_Led1Switch, 25);
    lv_obj_set_x(ui_Led1Switch, -343);
    lv_obj_set_y(ui_Led1Switch, -197);
    lv_obj_set_align(ui_Led1Switch, LV_ALIGN_CENTER);

    ui_Led2Switch = lv_switch_create(ui_LedCtrlTest);
    lv_obj_set_width(ui_Led2Switch, 50);
    lv_obj_set_height(ui_Led2Switch, 25);
    lv_obj_set_x(ui_Led2Switch, -342);
    lv_obj_set_y(ui_Led2Switch, -132);
    lv_obj_set_align(ui_Led2Switch, LV_ALIGN_CENTER);

    ui_Led3Switch = lv_switch_create(ui_LedCtrlTest);
    lv_obj_set_width(ui_Led3Switch, 50);
    lv_obj_set_height(ui_Led3Switch, 25);
    lv_obj_set_x(ui_Led3Switch, -341);
    lv_obj_set_y(ui_Led3Switch, -70);
    lv_obj_set_align(ui_Led3Switch, LV_ALIGN_CENTER);

    ui_GotoModbusTest = lv_button_create(ui_LedCtrlTest);
    lv_obj_set_width(ui_GotoModbusTest, 100);
    lv_obj_set_height(ui_GotoModbusTest, 50);
    lv_obj_set_x(ui_GotoModbusTest, 320);
    lv_obj_set_y(ui_GotoModbusTest, 193);
    lv_obj_set_align(ui_GotoModbusTest, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GotoModbusTest, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_GotoModbusTest, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GotoModbusTest, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GotoModbusTest, lv_color_hex(0x9D2525), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GotoModbusTest, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_GotoModbusTest, lv_color_hex(0x190F0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GotoModbusTest, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GotoModbusTest, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_GotoModbusTest);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "go");

    lv_obj_add_event_cb(ui_Bar1, ui_event_Bar1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Led1Switch, ui_event_Led1Switch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Led2Switch, ui_event_Led2Switch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Led3Switch, ui_event_Led3Switch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GotoModbusTest, ui_event_GotoModbusTest, LV_EVENT_ALL, NULL);

}

void ui_LedCtrlTest_screen_destroy(void)
{
    if(ui_LedCtrlTest) lv_obj_del(ui_LedCtrlTest);

    // NULL screen variables
    ui_LedCtrlTest = NULL;
    ui_Bar1 = NULL;
    ui_Led1Switch = NULL;
    ui_Led2Switch = NULL;
    ui_Led3Switch = NULL;
    ui_GotoModbusTest = NULL;
    ui_Label4 = NULL;

}

void ui_LedCtrlTest_screen_relocalize(void)
{
    // label widgets on screen

}
