// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_MODEBUSTEST_H
#define UI_MODEBUSTEST_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ModebusTest
extern void ui_ModebusTest_screen_init(void);
extern void ui_ModebusTest_screen_destroy(void);
extern void ui_ModebusTest_screen_relocalize(void);
extern lv_obj_t * ui_ModebusTest;
extern void ui_event_GotoScreen1(lv_event_t * e);
extern lv_obj_t * ui_GotoScreen1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Dropdown1;
extern void ui_event_GotoSdCardAndFatFsTest(lv_event_t * e);
extern lv_obj_t * ui_GotoSdCardAndFatFsTest;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_TextArea3;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

