// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ModebusTest = NULL;
lv_obj_t * ui_GotoScreen1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Dropdown1 = NULL;
lv_obj_t * ui_GotoSdCardAndFatFsTest = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_TextArea2 = NULL;
lv_obj_t * ui_TextArea3 = NULL;
lv_obj_t * ui_Label3 = NULL;
// event funtions
void ui_event_GotoScreen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_LedCtrlTest, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_LedCtrlTest_screen_init);
    }
}

void ui_event_GotoSdCardAndFatFsTest(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SdCardAndFatFsTest, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_SdCardAndFatFsTest_screen_init);
    }
}

// build funtions

void ui_ModebusTest_screen_init(void)
{
    ui_ModebusTest = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ModebusTest, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GotoScreen1 = lv_button_create(ui_ModebusTest);
    lv_obj_set_width(ui_GotoScreen1, 100);
    lv_obj_set_height(ui_GotoScreen1, 50);
    lv_obj_set_x(ui_GotoScreen1, -326);
    lv_obj_set_y(ui_GotoScreen1, 195);
    lv_obj_set_align(ui_GotoScreen1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GotoScreen1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_GotoScreen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GotoScreen1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_GotoScreen1, lv_color_hex(0x190F0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GotoScreen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GotoScreen1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_GotoScreen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Back");

    ui_Dropdown1 = lv_dropdown_create(ui_ModebusTest);
    lv_dropdown_set_options(ui_Dropdown1, "0x03\n0x04\n0x06\n0x10");
    lv_obj_set_width(ui_Dropdown1, 150);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, 227);
    lv_obj_set_y(ui_Dropdown1, 70);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_GotoSdCardAndFatFsTest = lv_button_create(ui_ModebusTest);
    lv_obj_set_width(ui_GotoSdCardAndFatFsTest, 100);
    lv_obj_set_height(ui_GotoSdCardAndFatFsTest, 50);
    lv_obj_set_x(ui_GotoSdCardAndFatFsTest, 320);
    lv_obj_set_y(ui_GotoSdCardAndFatFsTest, 193);
    lv_obj_set_align(ui_GotoSdCardAndFatFsTest, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GotoSdCardAndFatFsTest, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_GotoSdCardAndFatFsTest, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GotoSdCardAndFatFsTest, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GotoSdCardAndFatFsTest, lv_color_hex(0x9D2525), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GotoSdCardAndFatFsTest, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_GotoSdCardAndFatFsTest, lv_color_hex(0x190F0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GotoSdCardAndFatFsTest, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GotoSdCardAndFatFsTest, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_GotoSdCardAndFatFsTest);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "go");

    ui_TextArea2 = lv_textarea_create(ui_ModebusTest);
    lv_obj_set_width(ui_TextArea2, 150);
    lv_obj_set_height(ui_TextArea2, 38);
    lv_obj_set_x(ui_TextArea2, 222);
    lv_obj_set_y(ui_TextArea2, -35);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    if("1234567890" == "") lv_textarea_set_accepted_chars(ui_TextArea2, NULL);
    else lv_textarea_set_accepted_chars(ui_TextArea2, "1234567890");
    lv_textarea_set_placeholder_text(ui_TextArea2, "RegAddr");
    lv_textarea_set_password_mode(ui_TextArea2, true);

    ui_TextArea3 = lv_textarea_create(ui_ModebusTest);
    lv_obj_set_width(ui_TextArea3, 150);
    lv_obj_set_height(ui_TextArea3, 38);
    lv_obj_set_x(ui_TextArea3, 225);
    lv_obj_set_y(ui_TextArea3, 16);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
    if("1234567890" == "") lv_textarea_set_accepted_chars(ui_TextArea3, NULL);
    else lv_textarea_set_accepted_chars(ui_TextArea3, "1234567890");
    lv_textarea_set_placeholder_text(ui_TextArea3, "RegNumber");

    lv_obj_set_style_text_font(ui_TextArea3, &lv_font_montserrat_14, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_ModebusTest);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 197);
    lv_obj_set_y(ui_Label3, -114);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "text");

    lv_obj_add_event_cb(ui_GotoScreen1, ui_event_GotoScreen1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GotoSdCardAndFatFsTest, ui_event_GotoSdCardAndFatFsTest, LV_EVENT_ALL, NULL);

}

void ui_ModebusTest_screen_destroy(void)
{
    if(ui_ModebusTest) lv_obj_del(ui_ModebusTest);

    // NULL screen variables
    ui_ModebusTest = NULL;
    ui_GotoScreen1 = NULL;
    ui_Label2 = NULL;
    ui_Dropdown1 = NULL;
    ui_GotoSdCardAndFatFsTest = NULL;
    ui_Label5 = NULL;
    ui_TextArea2 = NULL;
    ui_TextArea3 = NULL;
    ui_Label3 = NULL;

}

void ui_ModebusTest_screen_relocalize(void)
{
    // label widgets on screen

}
