// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_MUSICPLAYER_H
#define UI_MUSICPLAYER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MusicPlayer
extern void ui_MusicPlayer_screen_init(void);
extern void ui_MusicPlayer_screen_destroy(void);
extern lv_obj_t * ui_MusicPlayer;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
