// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SDCARDANDFATFSTEST_H
#define UI_SDCARDANDFATFSTEST_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SdCardAndFatFsTest
extern void ui_SdCardAndFatFsTest_screen_init(void);
extern void ui_SdCardAndFatFsTest_screen_destroy(void);
extern void ui_SdCardAndFatFsTest_screen_relocalize(void);
extern lv_obj_t * ui_SdCardAndFatFsTest;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
extern void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_TabView2;
extern void ui_event_BackModbusTest(lv_event_t * e);
extern lv_obj_t * ui_BackModbusTest;
extern lv_obj_t * ui_Label6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

