// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_TextArea3 = NULL;
lv_obj_t * ui_Keyboard2 = NULL;
lv_obj_t * ui_Button7 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_ButtonHome3 = NULL;
// event funtions
void ui_event_ButtonHome3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_HomeScreen_screen_init);
    }
}

void ui_event_TextArea3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_TextArea3);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SaveToSd(e);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // Home button
    ui_ButtonHome3 = lv_button_create(ui_Screen3);
    lv_obj_set_width(ui_ButtonHome3, 90);
    lv_obj_set_height(ui_ButtonHome3, 40);
    lv_obj_align(ui_ButtonHome3, LV_ALIGN_TOP_LEFT, 10, 10);
    lv_obj_set_style_bg_color(ui_ButtonHome3, lv_color_hex(0x3AACB7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonHome3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ButtonHome3, 8, LV_PART_MAIN);
    lv_obj_t * label = lv_label_create(ui_ButtonHome3);
    lv_label_set_text(label, "⌂ Home");
    lv_obj_center(label);

    ui_TextArea3 = lv_textarea_create(ui_Screen3);
    lv_obj_set_width(ui_TextArea3, 363);
    lv_obj_set_height(ui_TextArea3, 140);
    lv_obj_set_x(ui_TextArea3, -149);
    lv_obj_set_y(ui_TextArea3, -100);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea3, "Input word...");

    ui_Keyboard2 = lv_keyboard_create(ui_Screen3);
    lv_obj_set_width(ui_Keyboard2, 555);
    lv_obj_set_height(ui_Keyboard2, 120);
    lv_obj_set_x(ui_Keyboard2, -63);
    lv_obj_set_y(ui_Keyboard2, 60);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);

    ui_Button7 = lv_button_create(ui_Screen3);
    lv_obj_set_width(ui_Button7, 100);
    lv_obj_set_height(ui_Button7, 50);
    lv_obj_set_x(ui_Button7, 305);
    lv_obj_set_y(ui_Button7, 70);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0x8E8585), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "save to SD");

    lv_obj_add_event_cb(ui_ButtonHome3, ui_event_ButtonHome3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea3, ui_event_TextArea3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_TextArea3 = NULL;
    ui_Keyboard2 = NULL;
    ui_Button7 = NULL;
    ui_Label2 = NULL;
    ui_ButtonHome3 = NULL;
}
