// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_SdCardAndFatFsTest = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_TabView2 = NULL;
lv_obj_t * ui_BackModbusTest = NULL;
lv_obj_t * ui_Label6 = NULL;
// event funtions
void ui_event_TextArea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextArea1);
    }
}

void ui_event_BackModbusTest(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ModebusTest, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_ModebusTest_screen_init);
    }
}

// build funtions

void ui_SdCardAndFatFsTest_screen_init(void)
{
    ui_SdCardAndFatFsTest = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SdCardAndFatFsTest, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Keyboard1 = lv_keyboard_create(ui_SdCardAndFatFsTest);
    lv_obj_set_width(ui_Keyboard1, 300);
    lv_obj_set_height(ui_Keyboard1, 120);
    lv_obj_set_x(ui_Keyboard1, -190);
    lv_obj_set_y(ui_Keyboard1, 25);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    ui_Button1 = lv_button_create(ui_SdCardAndFatFsTest);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, 38);
    lv_obj_set_y(ui_Button1, -109);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "save");

    ui_TextArea1 = lv_textarea_create(ui_SdCardAndFatFsTest);
    lv_obj_set_width(ui_TextArea1, 286);
    lv_obj_set_height(ui_TextArea1, 70);
    lv_obj_set_x(ui_TextArea1, -199);
    lv_obj_set_y(ui_TextArea1, -107);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "input word");

    ui_TabView2 = lv_tabview_create(ui_SdCardAndFatFsTest);
    lv_tabview_set_tab_bar_size(ui_TabView2, 50);
    lv_obj_set_width(ui_TabView2, 397);
    lv_obj_set_height(ui_TabView2, 200);
    lv_obj_set_x(ui_TabView2, -1137);
    lv_obj_set_y(ui_TabView2, 3);
    lv_obj_set_align(ui_TabView2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TabView2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BackModbusTest = lv_button_create(ui_SdCardAndFatFsTest);
    lv_obj_set_width(ui_BackModbusTest, 100);
    lv_obj_set_height(ui_BackModbusTest, 50);
    lv_obj_set_x(ui_BackModbusTest, -326);
    lv_obj_set_y(ui_BackModbusTest, 195);
    lv_obj_set_align(ui_BackModbusTest, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackModbusTest, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BackModbusTest, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BackModbusTest, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BackModbusTest, lv_color_hex(0x190F0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BackModbusTest, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BackModbusTest, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_BackModbusTest);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Back");

    lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BackModbusTest, ui_event_BackModbusTest, LV_EVENT_ALL, NULL);

}

void ui_SdCardAndFatFsTest_screen_destroy(void)
{
    if(ui_SdCardAndFatFsTest) lv_obj_del(ui_SdCardAndFatFsTest);

    // NULL screen variables
    ui_SdCardAndFatFsTest = NULL;
    ui_Keyboard1 = NULL;
    ui_Button1 = NULL;
    ui_Label1 = NULL;
    ui_TextArea1 = NULL;
    ui_TabView2 = NULL;
    ui_BackModbusTest = NULL;
    ui_Label6 = NULL;

}

void ui_SdCardAndFatFsTest_screen_relocalize(void)
{
    // label widgets on screen

}
