// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_HomeScreen_screen_init();
    ui_DeviceCtrl_screen_init();
    ui_ModbusSlave_screen_init();
    ui_FileEdit_screen_init();
    ui_FileExplorer_screen_init();
    ui_MusicPlayer_screen_init();
    ui_Information_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);

    lv_color_t white = lv_color_hex(0xFFFFFF);
    lv_obj_set_style_bg_color(ui_HomeScreen, white, LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_DeviceCtrl, white, LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_ModbusSlave, white, LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_FileEdit, white, LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_FileExplorer, white, LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_MusicPlayer, white, LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_Information, white, LV_PART_MAIN);

    lv_disp_load_scr(ui_HomeScreen);
}

void ui_destroy(void)
{
    ui_HomeScreen_screen_destroy();
    ui_DeviceCtrl_screen_destroy();
    ui_ModbusSlave_screen_destroy();
    ui_FileEdit_screen_destroy();
    ui_FileExplorer_screen_destroy();
    ui_MusicPlayer_screen_destroy();
    ui_Information_screen_destroy();
}
