// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Bar1ValueChangeEvent(lv_event_t * e);
void Bar1ValuePressedEvent(lv_event_t * e);
void Led1ClickedEvent(lv_event_t * e);
void Led2ClickedEvent(lv_event_t * e);
void Led3ClickedEvent(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
