// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"
#include <stdio.h>
#include <errno.h>
#include "../lvgl_event.h"

void Led1Change(lv_event_t * e)
{
	lvgl_event_send_toggle_led(1);
}

void Led2Change(lv_event_t * e)
{
	lvgl_event_send_toggle_led(2);
}

void Led3Change(lv_event_t * e)
{
    lvgl_event_send_toggle_led(3);
}

void SaveToSd(lv_event_t * e)
{
    const char *text = lv_textarea_get_text(ui_TextArea3);
    if (text && text[0])
    {
        int ret = lvgl_event_send_text(text);
        if (ret < 0)
            printf("ERROR: Failed to send text: %d\n", errno);
    }
}
